#pragma once
#include <switch.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum TimeZone {
    TimeZone_Invalid,
    TimeZone_AfricaBrazzaville,
    TimeZone_AfricaCasablanca,
    TimeZone_AfricaDakar,
    TimeZone_AfricaHarare,
    TimeZone_AfricaNairobi,
    TimeZone_AfricaWindhoek,
    TimeZone_AfricaCairo,
    TimeZone_AmericaAnchorage,
    TimeZone_AmericaAsuncion,
    TimeZone_AmericaBarbados,
    TimeZone_AmericaBogota,
    TimeZone_AmericaBuenos_Aires,
    TimeZone_AmericaCaracas,
    TimeZone_AmericaChicago,
    TimeZone_AmericaChihuahua,
    TimeZone_AmericaCiudad_Juarez,
    TimeZone_AmericaCosta_Rica,
    TimeZone_AmericaDenver,
    TimeZone_AmericaGodthab,
    TimeZone_AmericaHalifax,
    TimeZone_AmericaLima,
    TimeZone_AmericaLos_Angeles,
    TimeZone_AmericaManaus,
    TimeZone_AmericaMexico_City,
    TimeZone_AmericaMontevideo,
    TimeZone_AmericaNew_York,
    TimeZone_AmericaOjinaga,
    TimeZone_AmericaPhoenix,
    TimeZone_AmericaRecife,
    TimeZone_AmericaRegina,
    TimeZone_AmericaSantiago,
    TimeZone_AmericaSao_Paulo,
    TimeZone_AmericaSouth_Georgia,
    TimeZone_AmericaSt_Johns,
    TimeZone_AmericaTijuana,
    TimeZone_AsiaAlmaty,
    TimeZone_AsiaAmman,
    TimeZone_AsiaBaghdad,
    TimeZone_AsiaBaku,
    TimeZone_AsiaBangkok,
    TimeZone_AsiaBeirut,
    TimeZone_AsiaCalcutta,
    TimeZone_AsiaColombo,
    TimeZone_AsiaDhaka,
    TimeZone_AsiaDubai,
    TimeZone_AsiaIrkutsk,
    TimeZone_AsiaJerusalem,
    TimeZone_AsiaKabul,
    TimeZone_AsiaKarachi,
    TimeZone_AsiaKatmandu,
    TimeZone_AsiaKrasnoyarsk,
    TimeZone_AsiaKuala_Lumpur,
    TimeZone_AsiaKuwait,
    TimeZone_AsiaMagadan,
    TimeZone_AsiaOral,
    TimeZone_AsiaRiyadh,
    TimeZone_AsiaSeoul,
    TimeZone_AsiaShanghai,
    TimeZone_AsiaTaipei,
    TimeZone_AsiaTbilisi,
    TimeZone_AsiaTehran,
    TimeZone_AsiaTokyo,
    TimeZone_AsiaVladivostok,
    TimeZone_AsiaYakutsk,
    TimeZone_AsiaYekaterinburg,
    TimeZone_AsiaYerevan,
    TimeZone_AtlanticAzores,
    TimeZone_AtlanticCape_Verde,
    TimeZone_AtlanticReykjavik,
    TimeZone_AustraliaAdelaide,
    TimeZone_AustraliaBrisbane,
    TimeZone_AustraliaDarwin,
    TimeZone_AustraliaHobart,
    TimeZone_AustraliaPerth,
    TimeZone_AustraliaSydney,
    TimeZone_EuropeAthens,
    TimeZone_EuropeBelgrade,
    TimeZone_EuropeBerlin,
    TimeZone_EuropeCopenhagen,
    TimeZone_EuropeHelsinki,
    TimeZone_EuropeIstanbul,
    TimeZone_EuropeLondon,
    TimeZone_EuropeMadrid,
    TimeZone_EuropeMinsk,
    TimeZone_EuropeMoscow,
    TimeZone_EuropeSarajevo,
    TimeZone_PacificAuckland,
    TimeZone_PacificFiji,
    TimeZone_PacificGuam,
    TimeZone_PacificHonolulu,
    TimeZone_PacificMajuro,
    TimeZone_PacificMidway,
    TimeZone_PacificNoumea,
    TimeZone_PacificTongatapu
} TimeZone;

TimeZone convertTimeLocationNameToTimeZone(TimeLocationName* name);
time_t getLocalPosixTime(time_t posix_time, TimeZone name);

#ifdef __cplusplus
}
#endif